on:
  push:
    branches:
      - 'main'

name: Stable

jobs:
  test:
    name: Test project
    runs-on: macos-11 # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: cargo-bundle
  build:
    name: Build project
    permissions: write-all
    runs-on: macos-11 # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: goxkey-nightly
          path: target/release/bundle/osx/Gõ Key.app
      - name: Update nightly release
        uses: eine/tip@master
        with:
          tag: nightly-build
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: target/release/bundle/osx/*.*
