on:
  push:
    branches:
      - 'main'

name: Stable

jobs:
  test:
    name: Test project
    runs-on: macos-11 # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: cargo-bundle
  build:
    name: Build project
    permissions: write-all
    runs-on: macos-11 # add other OS later
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
      - name: Release binary
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create goxkey-nightly -p -t "GõKey Nightly"
          gh release upload "./target/release/bundle/osx/Gõ Key.app"
